part of 'program_watcher_cubit.dart';

@freezed
abstract class ProgramWatcherState with _$ProgramWatcherState {
  const factory ProgramWatcherState(
      {required List<Program> programs,
      required FirestoreFailure firestoreFailure,
      required List<Program> aspMember,
      required List<Program> nonMember,
      required FullDay fullDay,
      required Program fitness,
      required AdtService ptl,
      required AdtService pfl,
      required int groupPrice,
      required int fitnessPrice,
      required int totalPrice,
      required List<Session> sessions,
      required List<Session> fitnessSession,
      required List<Program> groupList,
      required bool isVisible,
      required int radioButtonGroupValue,
      required int ptlGroupValue,
      required int pflGroupValue,
      required int ptlPrice,
      required int pflPrice,
      required bool isFitness,
      required bool isFullDay,
      required String? programName,
      required String? sessionValue,
      required String ptlTimes,
      required String pflTimes,
      required int totalAspPrice}) = _ProgramWatcherState;

  factory ProgramWatcherState.initial() => ProgramWatcherState(
        programs: [],
        firestoreFailure: FirestoreFailure.none(),
        aspMember: [],
        nonMember: [],
        fullDay: FullDay.empty(),
        fitness: Program.empty(),
        ptl: AdtService.empty(),
        pfl: AdtService.empty(),
        groupPrice: 0,
        fitnessPrice: 0,
        totalPrice: 0,
        sessions: [],
        groupList: [],
        fitnessSession: [],
        isVisible: false,
        radioButtonGroupValue: 0,
        ptlGroupValue: 0,
        pflGroupValue: 0,
        ptlPrice: 0,
        pflPrice: 0,
        programName: null,
        sessionValue: null,
        isFitness: false,
        isFullDay: false,
        ptlTimes: '',
        pflTimes: '',
        totalAspPrice: 0,
      );
}
